### ISSUE TITLE
BGT & TBS cards in the same system?

### ISSUE THREAD

**Issue by emarr** [marcusbirkin/linux-tbs-drivers#1]
Hi Marcus

I've been happily using your BGT drivers for a while now and just noticed that you also have a repo here for TBS.

I have a TBS card that I'd like to use alongside the BGT.  Is this repo a combination of both drivers?

**Comment by marcusbirkin** [comment]
Hi,
No the BGT & TBS drivers can not co-exist.
Please also note that the TBS repo on my github is a copy for my convenience. The real repo maintained by crazycat is at https://bitbucket.org/CrazyCat/

I have dumped my BGT hardware because all the cards have proven to be very unreliable.
